input_dir: ${oc.env:MIMICIV_RAW_DIR}
cohort_dir: ${oc.env:MIMICIV_PRE_MEDS_DIR}

do_overwrite: true

batches:
  hosp/labevents: 14
  icu/chartevents: 30
  digits: 2

log_dir: ${cohort_dir}/.logs

# Hydra
hydra:
  job:
    name: pre_MEDS_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: ${log_dir}
  sweep:
    dir: ${log_dir}
